/* empty css                               */
import { c as createComponent, r as renderTemplate, f as renderComponent, m as maybeRenderHead } from '../astro_CglybI6J.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$Layout } from './404_CyfkxRdu.mjs';
import { $ as $$BtnMostrarProductos, a as $$BtnCotizar } from './adicionales_DUyaU4Ff.mjs';
import { Zoom, Fade } from 'react-awesome-reveal';

const $$Aluminio = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "path": "../", "title": "Perfiles de aluminio", "descriptions": 'aluminio l\xEDnea nacional ventajas fijas de 2", aluminio l\xEDnea nacional 3", aluminio l\xEDnea nacional ventana corrediza 1 1/2, aluminio l\xEDnea nacional ventana corrediza 2, aluminio l\xEDnea nacional ventana corrediza 3", aluminio l\xEDnea nacional ba\xF1os, aluminio l\xEDnea nacional batientes, aluminio l\xEDnea nacional ventila de proyecci\xF3n, aluminio l\xEDnea nacional vitrinas, aluminio l\xEDnea nacional angulos y tees, aluminio l\xEDnea nacional duelas, aluminio l\xEDnea nacional mosquiteros, aluminio l\xEDnea nacional molduras, aluminio l\xEDnea nacional louver, aluminio l\xEDnea nacional tubos cuadrados, aluminio l\xEDnea nacional tubos rectangulares, aluminio l\xEDnea nacional canal para domo, l\xEDnea espa\xF1ola serie 1400 abatible, l\xEDnea espa\xF1ola serie 3500 corredizo, l\xEDnea espa\xF1ola serie 4600 corredizo' }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<div class="container mx-auto py-10"> <div class="md:w-3/4 mx-auto px-10"> <div class="pb-4 text-center font-Bebas-Neue "> <h1 class="
                text-6xl 
                text-yellow-500 
                md:text-6xl 
                ">Perfiles de aluminio</h1> <p class="text-red-400 animate-pulse text-2xl">
Tenemos venta al corte</p> </div> ${renderComponent($$result2, "Zoom", Zoom, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Zoom" }, { "default": ($$result3) => renderTemplate` ${renderComponent($$result3, "BtnMostrarProductos", $$BtnMostrarProductos, {})} ` })} ${renderComponent($$result2, "Fade", Fade, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Fade" }, { "default": ($$result3) => renderTemplate` <div class="grid md:grid-cols-2 gap-4 mb-8"> <div class=""> <img class="object-scale-down border border-zinc-500 p-3" src="../images/producto/perfil-aluminio-espaniol.webp"> </div> <div> <h3 class="font-Bebas-Neue text-5xl mb-2 text-zinc-400">
Línea nacional</h3> ${renderComponent($$result3, "Fade", Fade, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Fade" }, { "default": ($$result4) => renderTemplate` <ul class="list-disc pl-5 text-xl"> <li>Ventajas fijas de 2" y 3"</li> <li>Ventana corrediza 1 1/2, 2" y 3"</li> <li>Baños</li> <li>Batientes</li> <li>Ventila de proyección</li> <li>Vitrinas</li> <li>Angulos y tees</li> <li>Duelas</li> <li>Mosquiteros</li> <li>Molduras</li> <li>Louver</li> <li>Tubos cuadrados</li> <li>Tubos rectangulares</li> <li>Canal para domo</li> </ul> ` })} </div> </div> ` })} ${renderComponent($$result2, "Fade", Fade, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Fade" }, { "default": ($$result3) => renderTemplate` ${renderComponent($$result3, "BtnCotizar", $$BtnCotizar, { "title": "Cotiza hoy mismo la l\xEDnea nacional", "message": "Hola! Estoy interesado en cotizar perfiles de aluminio de la l\xEDnea nacional" })} ` })} <div class="text-center animate-pulse pt-5 pb-10"> <i class="text-2xl fas fa-arrow-down"></i> </div> ${renderComponent($$result2, "Fade", Fade, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Fade" }, { "default": ($$result3) => renderTemplate` <div class="grid md:grid-cols-2 gap-4 mb-5"> <div class=""> <img class="object-contain border border-zinc-500 p-3" src="../images/producto/perfil-aluminio-nacional.webp"> </div> <div> <h3 class="font-Bebas-Neue text-5xl mb-2 text-zinc-400">
Línea española</h3> ${renderComponent($$result3, "Fade", Fade, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Fade" }, { "default": ($$result4) => renderTemplate` <ul class="list-disc pl-5 text-xl mb-5"> <li>Serie 1400 abatible</li> <li>Serie 3500 corredizo</li> <li>Serie 4600 corredizo</li> </ul> ` })} <h5 class="font-Bebas-Neue text-2xl animate-pulse text-yellow-500">Colores disponibles</h5> ${renderComponent($$result3, "Fade", Fade, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Fade" }, { "default": ($$result4) => renderTemplate` <ul class="list-disc pl-5 text-xl"> <li>Blanco</li> <li>Natural</li> <li>Duro e</li> <li>Electro</li> <li>Nogal</li> <li>Inox</li> </ul> ` })} </div> </div> ` })} ${renderComponent($$result2, "Fade", Fade, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Fade" }, { "default": ($$result3) => renderTemplate` ${renderComponent($$result3, "BtnCotizar", $$BtnCotizar, { "title": "Cotiza hoy mismo la l\xEDnea espa\xF1ola", "message": "Hola! Estoy interesado en cotizar perfiles de aluminio de la l\xEDnea espa\xF1ola" })} ` })} ${renderComponent($$result2, "Zoom", Zoom, { "client:visible": true, "client:component-hydration": "visible", "client:component-path": "react-awesome-reveal", "client:component-export": "Zoom" }, { "default": ($$result3) => renderTemplate` ${renderComponent($$result3, "BtnMostrarProductos", $$BtnMostrarProductos, {})} ` })} </div> </div> ` })}`;
}, "/Users/israelwong/Documents/Desarrollo/aluvitec.mx/src/pages/productos/aluminio.astro", void 0);

const $$file = "/Users/israelwong/Documents/Desarrollo/aluvitec.mx/src/pages/productos/aluminio.astro";
const $$url = "/productos/aluminio";

export { $$Aluminio as default, $$file as file, $$url as url };
