/* empty css                               */
import { c as createComponent, r as renderTemplate, f as renderComponent, m as maybeRenderHead } from '../astro_CLk474lC.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$Layout } from './404_BvsKi5Gj.mjs';

const $$Productos = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Productos", "descriptions": "Cristal, Procesos en cristal, Herrajes, Acr\xEDlicos, Policarbonato, Pl\xE1sticos para ba\xF1o, Domos" }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<div class="container mx-auto py-10"> <div class="text-center"> <h1 class="font-Bebas-Neue text-4xl md:text-6xl pb-3 text-yellow-700">Nuestros Productos</h1> <div class="mb-10"> <h3 class="font-Bebas-Neue text-2xl text-zinc-600">Tipos de cristal</h3> <ul class="text-sm"> <li><a target="_self" href="#">Flotado</a></li> <li><a target="_self" href="#">Reflectivo</a></li> <li><a target="_self" href="#">Esmerilado</a></li> <li><a target="_self" href="#">Espejo</a></li> <li><a target="_self" href="#">Laminado</a></li> </ul> </div> <div class="mb-10"> <h3 class="font-Bebas-Neue text-2xl text-zinc-600">Procesos en cristal</h3> <ul class="text-sm"> <li><a href="#" target="_self">Templado</a></li> <li><a href="#" target="_self">Canto pulido</a></li> <li><a href="#" target="_self">Grabado</a></li> <li><a href="#" target="_self">Bisel</a></li> <li><a href="#" target="_self">Cenefas</a></li> <li><a href="#" target="_self">Barrenos</a></li> <li><a href="#" target="_self">Saques</a></li> <li><a href="#" target="_self">Esmerilados</a></li> </ul> </div> <div class="pb-10"> <h3 class="font-Bebas-Neue text-2xl text-zinc-600">Perfiles de aluminio</h3> <ul class="text-sm"> <li><a href="#" target="_self">Línea nacional</a></li> <li><a href="#" target="_self">Línea española</a></li> <li><a href="#" target="_self">Venta al corte</a></li> <li><a href="#" target="_self">Colores blanco, natural, champagne, BTE, bronce, nogal</a></li> </ul> </div> <div class="pb-10"> <h3 class="font-Bebas-Neue text-2xl text-zinc-600">Herrajes</h3> <ul class="text-sm"> <li><a href="#" target="_blank">Para cristal templado</a></li> <li><a href="#" target="_blank">Para cancelería de aluminio nacional y española</a></li> </ul> </div> <div class="pb-10"> <h3 class="font-Bebas-Neue text-2xl text-zinc-600">Productos adicionales</h3> <ul class="text-sm"> <li><a href="#" target="_blank">Acrílicos</a></li> <li><a href="#" target="_blank">Policarbonato</a></li> <li><a href="#" target="_blank">Plásticos para baño</a></li> <li><a href="#" target="_blank">Domos</a></li> </ul> </div> </div> </div> ` })}`;
}, "/Users/israelwong/Documents/Desarrollo/aluvitec.mx/src/pages/productos.astro", void 0);

const $$file = "/Users/israelwong/Documents/Desarrollo/aluvitec.mx/src/pages/productos.astro";
const $$url = "/productos";

export { $$Productos as default, $$file as file, $$url as url };
